### ISSUE TITLE
Sample_himax_firmware_for_image_sensor_checking

### ISSUE THREAD

**Issue by psharana** [HimaxWiseEyePlus/WE_I_Plus_User_Examples#4]
Hello everyone,
Please provide sample firmware source code (along with executable) of configuring image sensor register only.
Provide details of 
1. How to build it (linux, windows)
2. Procedure to flash executable to himax Eval board
3. what is expected results and where results are observed (in terminal or command window or ..)

My main intention is I have to load existing binary into himax board and check results.
Later will modify registers and build it and flash my changed code to board and will check the results.
Will compare both results.
This will gives hands on experience on himax board.

**Comment by bigcat-himax** [comment]
Hi, Psharana:

HIMAX WE1 EVB is mainly use for ML, which we provide only default image sensor setting to resolution 640x480 raw and jpeg image. 

Thanks.

**Comment by psharana** [comment]
Himax we-i-plus board is also used for motion detection right....?
I am interested on motion detection and I am not interested in using edge impulse tools. 
I even got motion detection setting_files from himax team. How to validate those settings.....I want more details on source code and tool and procedure followed for building.

**Comment by bigcat-himax** [comment]
Hi, Psharana:

currently, we use HIMAX WE1 EVB's motion detection feature, not sensor's. 

Thanks.
