### ISSUE TITLE
Pc tool source code

### ISSUE THREAD

**Issue by JJunHan** [HimaxWiseEyePlus/WE_I_Plus_User_Examples#5]
Hi,

May i check if it is possible to provide the source code for the linux version of the PC tool for further development? 

Thanks.

**Comment by kris-himax** [comment]
@JJunHan Hi
What is your purpose about the PC tool? 
If you want to receive SPI data from HIMAX_WE1_EVB, you can use the following code.
https://github.com/HimaxWiseEyePlus/bsp_tflu/tree/master/SPI_Tool

Thanks.

**Comment by JJunHan** [comment]
@kris-himax hi kris, I was planning to use the PC tool to visualize the bounding boxes and add into other forms of data like class labels. If possible, i would the source code to reference how the meta data structure is being converted and how the image is being displayed.

**Comment by kris-himax** [comment]
@JJunHan hi
You can see the meta data structure format at line 54 to 65 in the HIMAX_Yolo_Fastest_Person_Detection_Example repository.
https://github.com/HimaxWiseEyePlus/WE_I_Plus_User_Examples/blob/main/HIMAX_Yolo_Fastest_Person_Detection_Example/yolo_fastest/main_functions.cc#L54

At the SPI_Tool repository, you can receive the same meta data structure pointer to get the meta data information.
https://github.com/HimaxWiseEyePlus/bsp_tflu/blob/master/SPI_Tool/DrvSPIs.cc#L39
