### ISSUE TITLE
example of WE-I (DSI_6537)

### ISSUE THREAD

**Issue by kevin789654tw** [HimaxWiseEyePlus/WE_I_Plus_User_Examples#7]
Dear Kris：

Hi, it's me Kevin again. Recently, I'm try to run example of Smart Agriculture with using WE-I (DSI_6537). I had followed the step in "[SmartAgriculture-example](https://github.com/HimaxWiseEyePlus/WE_I_Plus_User_Examples/tree/main/SmartAgriculture-example)". But I'm stuck in last step. 

The last step said use Himax Flash Tool to flash the out.img in image_gen_linux folder with command `himax-flash-tool --(firmware-path)/image_gen_linux/out.img`. 

So I put my path which image_gen_linux folder is like this : `himax-flash-tool --/home/bcrkevin/Documents/DSI_6537/Example/WE_I_Plus_User_Examples/SmartAgriculture-example/image_gen_linux/out.img`. But it's not work. 

And I also found similar command `himax-flash-tool --firmware-path image_gen_linux/out.img` in "[running-your-impulse-himax](https://docs.edgeimpulse.com/docs/deployment/running-your-impulse-locally/running-your-impulse-himax)". 

I was wondering, What the correct "firmware-path" should I fill in. Thank you.

Best Regards
Kevin LIn
博誠電子股份有限公司
Brocere Electronics Co. Ltd.
http://www.brocere.com/

**Comment by kris-himax** [comment]
@kevin789654tw hi
1. list your USB com number
```
ls /sys/bus/usb-serial/devices/ -ltra
```
2. In my case the WE-I is on /dev/ttyUSB0
```
sudo chmod 777 /dev/ttyUSB0
```
3. Flashing
You'll need to install the Edge Impulse CLI. Reference here https://docs.edgeimpulse.com/docs/edge-impulse-cli/cli-installation .
Go under the folder you generated the out.img file
```
himax-flash-tool -f out.img
```

![Screenshot from 2022-06-24 11-25-37](https://user-images.githubusercontent.com/87454575/175456130-dcdfd739-0884-4605-ad50-da4e2bc6f79e.png)

**Comment by kevin789654tw** [comment]
Hi, Kris：

My USB com number :
![Screenshot from 2022-06-23 23-19-21](https://user-images.githubusercontent.com/46592538/175478963-13024ff9-31bf-4dbc-8deb-cf3e725a750c.png)

I flashed my WE-I like this :
![Screenshot from 2022-06-23 23-23-10](https://user-images.githubusercontent.com/46592538/175478984-96250c23-178a-4aac-9803-9006e3ae9ec9.png)

But in my minicom shows that nothing can run :
![Screenshot from 2022-06-23 23-31-29](https://user-images.githubusercontent.com/46592538/175479007-e6fd7da6-cff4-4521-affe-4480b10a8bb8.png)

I've wrote some notes. Here are my steps and reference URLs:
https://hackmd.io/@kevin789654tw/BJahFUWcq

Also, I was wondering, is there something wrong with my model creation? Here is my project in Edge Impulse.
https://studio.edgeimpulse.com/public/114087/latest

**Comment by kris-himax** [comment]
@kevin789654tw hi
It seems like that your ccs811 initial fail.
Make sure that you follow the Prerequisite https://github.com/HimaxWiseEyePlus/WE_I_Plus_User_Examples/tree/main/SmartAgriculture-example#prerequisites to install [SparkFun Environmental Combo Breakout - CCS811/BME280 (Qwiic)](https://www.sparkfun.com/products/14348) and [LoRa - REYAX RYLR896](https://reyax.com/products/rylr896/) on WE-I.

**Comment by kevin789654tw** [comment]
Thank you, Kris. 
I misunderstood that SmartAgriculture-example can do without setting SparkFun Environment and LoRa. I'm totally wrong. Thanks for helping me out.
